[package]
name = "yetanotherclown/planck"
description = "An Agnostic Scheduler for ECS"
license = "MIT"
authors = ["YetAnotherClown"]
version = "0.2.0-rc.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
homepage = "https://yetanotherclown.github.io/planck"
repository = "https://github.com/yetanotherclown/planck"

exclude = [
    "src/__*__",
    "src/__*__/*",
    "package.json",
    "*.tgz",
    "*.zip",
]
include = ["wally.lock"]
